export const BASE_MAP_IDS = ["verdantCrossroads", "bareDuel", "openClaims", "campRush", "combatArena"] as const;
export const NON_SCORE_RICH_MAP_IDS = ["stagHollow", "willowCircuit", "quarrySong"] as const;

export const AUTHORED_RICH_SCORE_MAP_IDS = [
  "wildMarches",
  "emberFen",
  "thornedDelta",
  "silverRidge",
  "ashVale",
  "reedBasin",
  "frostMeadow",
  "sunkenOrchard",
  "cedarPass",
  "moonlitCauseway",
  "briarToll",
  "amberReach",
  "lichenCrown",
  "obsidianBrook",
  "mistHarbor",
  "sableRun",
  "fernBarrow",
  "glassmereFord",
  "cinderHeath",
  "runeMeadow",
  "saltwindBasin",
  "verdigrisSpire",
  "pineTangle",
  "pearlBog",
  "ironMoss",
  "duskGrove",
  "hollowFord",
  "copperWeald",
  "opalFen",
  "ivoryTarn",
  "mallowRun",
  "graniteBloom",
  "rainbarrow",
  "umberCauseway",
  "tealFissure",
  "saffronFen",
  "mirrorHeath",
  "basaltMeadow",
  "juniperDelta",
  "ochreRidge",
  "quietMire",
  "lanternFord",
  "viridianToll",
  "marbleGrove",
  "sundialReach",
  "heatherCircuit",
  "chalkFen",
  "russetBrook",
  "celadonPass",
  "plumTarn",
  "wispQuarry",
  "brackenFord",
  "mossglassRun",
  "auricDelta",
  "bluebellHeath",
  "cairnCauseway",
  "foxgloveMire",
] as const;

export const GENERATED_RICH_SCORE_MAP_IDS = [
  "cobaltVale",
  "pearlCircuit",
  "yarrowFen",
  "copperFen",
  "cloverRun",
  "hazelCircuit",
  "spruceCircuit",
] as const;

export const RICH_SCORE_MAP_IDS = [...AUTHORED_RICH_SCORE_MAP_IDS, ...GENERATED_RICH_SCORE_MAP_IDS] as const;
export const MAP_IDS = [...BASE_MAP_IDS, ...NON_SCORE_RICH_MAP_IDS, ...RICH_SCORE_MAP_IDS, "grandThirty"] as const;
